import type { EventItem } from "./types";

// Names as printed on the official poster. Add poster, description, category, time, etc. per event; empty fields stay hidden.
export const events: EventItem[] = [
  {
    id: "ad-act",
    name: "AD ACT",
    poster: "/assets/events/ad-act.jpg",
    category: "Dramatics",
    description: "AD ACT by Abhinay, The Dramatics Society.",
    contact: "Abhinay — The Dramatics Society",
  },
  {
    id: "aerius",
    name: "AERIUS",
    poster: "/assets/events/aerius.jpg",
    category: "Drone Programming",
    description: "Aerius — Drone Programming Challenge by UAV & Drone Club.",
    date: "October 1, 2026",
    startTime: "1 Oct, 2:00 PM",
    endTime: "1 Oct, 3:30 PM",
    venue: "JC Bose Hall, ELC, JNU",
    contact: "Dr. G. Renuka Devi, Dr. Ashwini K. Arya / Rohan Dev, Priyanshu Bhardwaj",
  },
  {
    id: "blind-coding",
    name: "BLIND CODING",
    poster: "/assets/events/blind-coding.jpg",
    category: "Coding",
    description: "Blind Coding Challenge by LOOP, the developers' club. A competition where one person is the hand and the other is the brain.",
    date: "October 1, 2026",
    venue: "ELC, JNU",
    teamSize: "2",
  },
  {
    id: "blueprint",
    name: "BLUEPRINT",
    poster: "/assets/events/blueprint.jpg",
    description: "Blueprint Final Round by VOLT.",
    date: "October 1, 2026",
    startTime: "1 Oct, 11:00 AM",
    endTime: "1 Oct, 1:00 PM",
    venue: "ELC, JNU",
    contact: "Dr. B. Lakshmi Priya, Dr. Pushpendra Singh / Aryan Mishra, Abhishek Gupta (7357584878)",
  },
  {
    id: "cold-start",
    name: "CO.L.D START",
    poster: "/assets/events/cold-start.jpg",
    posterPosition: "50% 30%",
    category: "ML Hackathon",
    description: "Co.L.D Start ML Hackathon. Real data. Real problems. Build your model — train, experiment and predict on a dataset provided on Kaggle, then submit and compete on the leaderboard. Inspired by Amazon ML Challenge, Flipkart Gridlock, Kaggle competitions and more.",
    date: "28 Sept – 1 Oct 2026",
    startTime: "28 Sept, 11:00 AM",
    endTime: "1 Oct, 11:00 AM",
    venue: "Online (Kaggle)",
  },
  { id: "core-of-everything", name: "CORE OF EVERYTHING" },
  {
    id: "gamepop",
    name: "GAMEPOP",
    poster: "/assets/events/game-pop.jpg",
    category: "Game Development",
    description: "Game Pop — Game Development Challenge by Ephirium.",
    date: "October 1, 2026",
    startTime: "1 Oct, 11:00 AM",
    endTime: "1 Oct, 1:00 PM",
    venue: "Ramanujan, ELC, JNU",
    contact: "Dr. Rituraj Singh / Turbash Negi (7078960722), Aarush Mittal (8077882726)",
  },
  {
    id: "guesstimate",
    name: "GUESSTIMATE",
    poster: "/assets/events/guesstimate.jpg",
    category: "Management & Consulting",
    description: "Guesstimate by MC², the Management and Consulting Club. You Can't Google Your Way Out of This — estimate, reason and defend your numbers.",
    date: "October 1, 2026",
    startTime: "1 Oct, 12:00 PM",
    endTime: "1 Oct, 1:00 PM",
    venue: "JC Bose Hall, ELC, JNU",
    contact: "Dr. Deepak Sharma, Dr. Rituraj Singh / Ramji, Devananda Sreekumar",
  },
  {
    id: "pitch-a-part",
    name: "PITCH-A-PART",
    poster: "/assets/events/pitch-a-part.jpeg",
    category: "Entrepreneurship",
    description: "Pitch-A-Part — A Business-Model Deep-Dive Round by Phoenix, The Entrepreneurship Club. Research. Defend. Pitch like you built it.",
    date: "October 1, 2026",
    startTime: "1 Oct, 4:00 PM",
    endTime: "1 Oct, 5:30 PM",
    venue: "Ramanujan, ELC, JNU",
    contact: "Phoenix — The Entrepreneurship Club",
  },
  {
    id: "raaz-riwaayat-aur-riwaaz",
    name: "RAAZ, RIWAAYAT AUR RIWAAZ",
    poster: "/assets/events/raaz.jpg",
    category: "Quiz",
    description: "Raaz, Riwaayat aur Riwaaz — A Quiz on Mysteries, Heritage and Traditions by MegaWhats. Test your knowledge. Uncover mysteries. Explore stories, heritage & traditions.",
    date: "October 1, 2026",
    startTime: "1 Oct, 3:30 PM",
    endTime: "1 Oct, 5:30 PM",
    venue: "JC Bose Hall, ELC, JNU",
    contact: "MegaWhats — JNU School of Engineering",
  },
  {
    id: "robo-soccer",
    name: "ROBO SOCCER",
    poster: "/assets/events/robo-soccer.jpg",
    category: "Robotics",
    description: "Robo Car Workshop by DeRobotica — Innovate | Build | Program. Hands-on workshop to build and program your own robo car.",
    date: "September 23, 2026",
    startTime: "23 Sept, 4:30 PM",
    venue: "JC Bose Hall, ELC, JNU",
    contact: "Dr. G. Renuka Devi, Dr. Pushpendra Singh",
  },
  {
    id: "sound-check",
    name: "SOUND-CHECK",
    poster: "/assets/events/sound-check.jpg",
    category: "Music",
    description: "Soundcheck — The Ultimate Music Challenge by Bandish, the Music Society. Guess it. Complete it. Challenge it. 3 rounds, teams of 4, one winner.",
    date: "October 1, 2026",
    startTime: "1 Oct, 6:30 PM",
    venue: "J.C. Bose Hall, ELC, SOE, JNU",
    teamSize: "4",
    contact: "Bandish — The Music Society",
  },
  {
    id: "space-athon",
    name: "SPACE-ATHON",
    poster: "/assets/events/space-athon.jpg",
    category: "Space",
    description: "Space-athon — Elimination Round by Antariksh, the Space Club.",
    date: "September 28, 2026",
    startTime: "28 Sept, 6:00 PM",
    endTime: "28 Sept, 7:00 PM",
    venue: "Janki Ammal Hall, ELC, JNU",
    contact: "Antariksh — The Space Club",
  },
  {
    id: "the-crucible",
    name: "THE CRUCIBLE",
    poster: "/assets/events/crucible.jpg",
    category: "Debate",
    description: "The Crucible — Defend the Infamous by Nuqta, the Literary and Debating Society. Speak. Listen. Disagree. Respect. Argue, question, explore, evolve.",
    date: "October 1, 2026",
    startTime: "1 Oct, 4:00 PM",
    endTime: "1 Oct, 5:30 PM",
    venue: "Janki Ammal Hall, SOE, JNU",
    prize: "Unique Prizes",
    contact: "Nuqta — The Literary and Debating Society, SOE, JNU",
  },
  {
    id: "treasure-hunt",
    name: "TREASURE HUNT",
    poster: "/assets/events/treasure-hunt.jpg",
    category: "Photography",
    description: "Treasure Hunt by Drushyam, the Photography & Film Society. Every frame hides a clue, every clue leads to the treasure.",
    date: "October 1, 2026",
    startTime: "1 Oct, 10:00 AM onwards",
    venue: "ELC, JNU",
    contact: "Dr. Ankit Kumar Jaiswal (Faculty Coordinator)",
  },
];
