import type { EventItem } from "./types";

// Names as printed on the official poster. Add poster, description, category, time, etc. per event; empty fields stay hidden.
export const events: EventItem[] = [
  { id: "ad-act", name: "AD ACT" },
  { id: "aerius", name: "AERIUS" },
  {
    id: "blind-coding",
    name: "BLIND CODING",
    poster: "/assets/events/blind-coding.jpg",
    category: "Coding",
    description: "Blind Coding Challenge by LOOP, the developers' club. A competition where one person is the hand and the other is the brain.",
    date: "October 1, 2026",
    venue: "ELC, JNU",
    teamSize: "2",
  },
  { id: "blueprint", name: "BLUEPRINT" },
  {
    id: "cold-start",
    name: "CO.L.D START",
    poster: "/assets/events/cold-start.jpg",
    posterPosition: "50% 30%",
    category: "ML Hackathon",
    description: "Co.L.D Start ML Hackathon. Real data. Real problems. Build your model — train, experiment and predict on a dataset provided on Kaggle, then submit and compete on the leaderboard. Inspired by Amazon ML Challenge, Flipkart Gridlock, Kaggle competitions and more.",
    date: "28 Sept – 1 Oct 2026",
    startTime: "28 Sept, 11:00 AM",
    endTime: "1 Oct, 11:00 AM",
    venue: "Online (Kaggle)",
  },
  { id: "core-of-everything", name: "CORE OF EVERYTHING" },
  { id: "gamepop", name: "GAMEPOP" },
  { id: "guesstimate", name: "GUESSTIMATE" },
  { id: "pitch-a-part", name: "PITCH-A-PART" },
  { id: "raaz-riwaayat-aur", name: "RAAZ RIWAAYATH AUR RIVAAZ" },
  { id: "robo-soccer", name: "ROBO SOCCER" },
  {
    id: "sound-check",
    name: "SOUND-CHECK",
    poster: "/assets/events/sound-check.jpg",
    category: "Music",
    description: "Soundcheck — The Ultimate Music Challenge by Bandish, the Music Society. Guess it. Complete it. Challenge it. 3 rounds, teams of 4, one winner.",
    date: "October 1, 2026",
    startTime: "1 Oct, 6:30 PM",
    venue: "J.C. Bose Hall, ELC, SOE, JNU",
    teamSize: "4",
    contact: "Bandish — The Music Society",
  },
  {
    id: "space-athon",
    name: "SPACE-ATHON",
    poster: "/assets/events/space-athon.jpg",
  },
  { id: "the-crucible", name: "THE CRUCIBLE" },
  {
    id: "treasure-hunt",
    name: "TREASURE HUNT",
    poster: "/assets/events/treasure-hunt.jpg",
    category: "Photography",
    description: "Treasure Hunt by Drushyam, the Photography & Film Society. Every frame hides a clue, every clue leads to the treasure.",
    date: "October 1, 2026",
    startTime: "1 Oct, 10:00 AM onwards",
    venue: "ELC, JNU",
    contact: "Dr. Ankit Kumar Jaiswal (Faculty Coordinator)",
  },
];
